name: deploy-manifests

on:
  push:
    branch:
      - master:
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # NOTE: Authenticate and install doctl
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # NOTE: Get connection credentials for DO k8s cluster
      # TODO: Create cluster in DO
      # - run: doctl kubernetes cluster kubeconfig save <cluster_name>
      # NOTE: Apply all config files to cluster
      # TODO: Better way to add files
      # - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
